# Generated by Django 2.1.3 on 2018-11-14 10:38

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 10, 38, 34, 968866, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='game',
            name='owners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 10, 38, 34, 968831, tzinfo=utc)),
        ),
    ]
