# Generated by Django 2.1.3 on 2018-11-19 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='added_by',
            field=models.ForeignKey(on_delete=models.SET('deleted'), related_name='added_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=models.SET('deleted'), related_name='modified_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='owners',
            field=models.ManyToManyField(related_name='owned_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
